theme: jekyll-theme-cayman

# Optional settings for the Cayman theme
title: Body Buddy 💪
description: Introducing Body Buddy, the ultimate food wingman! Not only does it track your calories, but it's also a whiz at recognizing the nutritional value of your meals just by looking at them. So you can finally stop guessing what's in that salad and start getting fit with a friend who's got your back (and your plate)!
show_downloads: true

# Setting for using a subdirectory as the root
baseurl: /docs
