# Android Build GitHub Actions Workflow
name : Android Build

# Trigger the workflow when code is pushed to the main, 456849, 460554, or 463590 branch
on:
  push:
    branches:
      - 'main'
      - '456849'
      - '460554'
      - '463590'

# Define two jobs: test and apk
jobs:
  # The test job runs unit tests
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      # Check out the source code
      - name: Checkout
        uses: actions/checkout@v2

      # Set up JDK 11
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      # Run the Gradle "test" task to run unit tests
      - name: Run Tests
        run: bash ./gradlew test --stacktrace

  # The apk job builds and generates the debug APK
  apk:
    name: Generate APK
    # Wait for the "test" job to complete before running
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Check out the source code
      - name: Checkout
        uses: actions/checkout@v2

      # Set up JDK 11
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      # Run the Gradle "assembleDebug" task to build the debug APK
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace

      # Upload the debug APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
